apiVersion: v1
kind: Service
metadata:
  name: crypto-intel-app
  namespace: crypto-intel
  labels:
    app: crypto-intel-app
    component: application
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP
  selector:
    app: crypto-intel-app
    component: application
  sessionAffinity: None
